insert into [Categories] ([Name]) values(N'תלמוד')
insert into [Books] ([Name], [Category]) values (N'ברכות', 1)
insert into [Resources] ([Book], [Page], [Path]) values (1, 1, '1.jpg')

insert into [AuthorKinds] ([Name]) values(N'ראשונים')
insert into [AuthorKinds] ([Name]) values(N'אחרונים')
insert into [AuthorKinds] ([Name]) values(N'פוסקים')
insert into [AuthorKinds] ([Name]) values(N'מקובלים')
insert into [AuthorKinds] ([Name]) values(N'גאונים')
insert into [AuthorKinds] ([Name]) values(N'תנאים')
insert into [AuthorKinds] ([Name]) values(N'אמוראים')

insert into [Authors] ([First], [Last], [AuthorKind]) values (N'שלמה', N'זלמן', 1)
insert into [Authors] ([First], [Last], [AuthorKind]) values (N'אברהם', N'יצחק', 2)
insert into [Authors] ([First], [Last], [AuthorKind]) values (N'משה', N'יוסף', 3)
insert into [Authors] ([First], [Last], [AuthorKind]) values (N'שמן', N'זית', 4)
insert into [Authors] ([First], [Last], [AuthorKind]) values (N'רום', N'צימוקים', 5)
insert into [Authors] ([First], [Last], [AuthorKind]) values (N'ביצה', N'עלומה', 6)